Create database Predio;
GO

CREATE TABLE Usuarios(
	Legajo INT PRIMARY KEY IDENTITY(1000,1) NOT NULL,
	Rol SMALLINT NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE,
	Telefono VARCHAR(40) NOT NULL,
);
GO

CREATE TABLE TipoCanchas(
	Id SMALLINT PRIMARY KEY  IDENTITY(1,1) NOT NULL,
	Nombre VARCHAR(100) NOT NULL,
);
GO 

CREATE TABLE Canchas(
	Id SMALLINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Precio DECIMAL NOT NULL CHECK(Precio > 0),
	IdTipoCancha SMALLINT FOREIGN KEY REFERENCES TipoCanchas(Id),
	Descripcion VARCHAR(200) NOT NULL,
	UrlImagen VARCHAR(200) NOT NULL,
);
GO